spring:
  application:
    name: hanaro
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      enabled: true
      max-file-size: 512KB
      max-request-size: 3MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # create-drop, update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}  # 1시간
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7일

upload:
  path: src/main/resources/static/upload

logging:
  level:
    org.springframework.security.web: trace

management:
  server:
    port: 8080 # 사용하는 포트 번호
  endpoints:
    web:
      base-path: /management
      exposure: # 엔드포인트 노출 설정
        include: "*" # health,metrics,beans,env
  endpoint:
    health:
      show-details: always
    env:
      show-values: WHEN_AUTHORIZED
      keys-to-sanitize:
        - "password"
        - "secret"
        - "hey"
        - "token"
        - ".credentials"